export enum PEER_EVENTS {
	ON_CONNECTION_STATE_CHANGED = 'ON_CONNECTION_STATE_CHANGED',
	ON_SIGNALING_STATE_CHANGE = 'ON_SIGNALING_STATE_CHANGE',
	ON_ICE_CANDIDATE = 'ON_ICE_CANDIDATE',
	ON_ICE_GATHERING_STATE_CHANGE = 'ON_ICE_GATHERING_STATE_CHANGE',
	ON_NEGOTIATION_NEEDED = 'ON_NEGOTIATION_NEEDED',
	ON_TRACK = 'ON_TRACK',
	ON_DATA_CHANNEL = 'ON_DATA_CHANNEL'
}

export enum SDP_TYPE {
	OFFER = 'offer',
	ANSWER = 'answer',
	PRANSWER = 'pranswer'
}
